version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
    - ./ngnix.conf:/etc/nginx/conf.d/default.conf
    - ./build:/usr/share/nginx/html
    depends_on:
     - app