version: '3.8'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./build:/usr/share/nginx/html
    depends_on:
      - app